function A = createA(meshSize, k, h, P, L, A_t, T_w, T_ar)
    dx = L/meshSize;
    m = h*P/(k*A_t);
    A = sparse(meshSize,meshSize);
    ons = ones(meshSize-1,1);
    rowCol = linspace(1,meshSize-1,meshSize-1)';
    A = A+sparse(rowCol,rowCol+ons,-ons/dx,meshSize,meshSize);
    %A = A+sparse(diag(-ones(meshSize-1,1)/dx,1));
    A = A+sparse(rowCol+ons,rowCol,-ons/dx,meshSize,meshSize);
    %A = A+sparse(diag(-ones(meshSize-1,1)/dx,-1));
    ons = ones(meshSize,1);
    rowCol = linspace(1,meshSize,meshSize)';
    A = A+sparse(rowCol,rowCol,ons*(2/dx+m*dx));
    %A = A+sparse(diag(ones(meshSize,1)*(2/dx+m*dx),0));
    A(1,1) = 3/dx+m*dx;
    A(1,2) = -1/dx;
    A(meshSize,meshSize) = h/k/(1+h*dx/(2*k))+1/dx+m*dx;
    A(meshSize,meshSize-1) = -1/dx;
end